version: '2.4'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app:delegated
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spacetrouble
      POSTGRES_HOSTNAME: db:5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spacetrouble
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
